### ISSUE TITLE
Missing <define> in the RELAX-NG grammar?

### ISSUE THREAD

**Issue by siefkenj** [rbeezer/pretext#10]
I am poking through the RELAX-NG grammar here https://raw.githubusercontent.com/PreTeXtBook/pretext/master/schema/pretext.rng and it looks like `Group` and `Configuration` are only defined with `combine="choice"` but they have no base definition. Is this allowed? (If it is, can you tell me the rules? Does it translate to `<choice><empty /><...the new definition></choice>`?

**Comment by rbeezer** [comment]
The grammar begins with  `schema/pretext.xml`  (as mentioned in the README?).

It uses compact notation (RNC).  So I can't read RNG and have no idea what you are talking about.  ;-) ;-) ;-)

Schema is not in great shape, do not consider it as gospel.

**Comment by siefkenj** [comment]
Ah. In compact from what I said translates to "all definition of `Group` are defined as `|=` without a `=` definition". I read through the RELAX-NG spec last night and it appears what you have is valid. The only thing that's forbidden is a mix of combine types (e.g. a mix of `|=` and `&=`).

How far off is the schema. I am trying to do some automatic code generation via the schema and I would very much like it to be gospel...

**Comment by rbeezer** [comment]
Good.  ;-)  I think `Group` and `Composition` are general things, not part of PreTeXt-specifics.  The RNG was built by `trang` which is an invertible mapping to/from  RNG/RNC.

The schema needs to be tightened in some places, loosened in others.  Whole pieces that are not final are missing, `worksheet` and `interactive`, for instance.  `docinfo` is slowly being reduced, so I've not even really attempted that until it settles down.  That sort of thing.
