### ISSUE TITLE
[Overhaul] data-contains-math-knowls="" is set even if there isn't a math knowl

### ISSUE THREAD

**Issue by siefkenj** [rbeezer/pretext#11]
An attribute `data-contains-math-knowls=""` is supposed to be added to math content that contains a knowl. However, it appears to be set on all math content, whether or not it contains a knowl...

**Comment by rbeezer** [comment]
Stopped writing the empty ones.  Limited testing looks like it is under control.  At bf453f1c0861c4bbd1c8417ffd8962dd95c7aa81

Thanks!
