### ISSUE TITLE
Incorrect Javascript in MathJax configuration

### ISSUE THREAD

**Issue by siefkenj** [rbeezer/pretext#9]
I just tried out the new flag and it outputs
```
/* Mathjax typesetting operation is under the control of React */
  startup: {
    typeset: false;
  },
```
in the MathJax configuration. However `typeset: false;` should be `typeset: false,`

**Comment by rbeezer** [comment]
Fixed just now at defdbc0cf3ca6654b8cbadeaf3bab6cb9cfe6fc6

Sorry, I think I thought I was wrting CSS at that moment.  :-(
